### ISSUE TITLE
Why require sudo in cleanup?

### ISSUE THREAD

**Issue by barbazul** [netz98/n98-deployer#1]
I am building a deploy pipeline and so far I have found no need to grant sudo access to the deploy user.

However the Cleanup task uses sudo to remove old release folders. Is there any need I am not seeing?

Release folders are being generated with the same user that runs the pipeline commands and any user-generated content (which would be owned by apache) are in shared folders...

**Comment by mwr** [comment]
Well, that's a good question. From the top of my head I would guess we included it to make sure that directories are really removed during cleanup. As this implementation is derived from our interal setup, this might be a relict of the initial phase of setting up our deployment.
In some situations we had issues when a file was created within a release folder that was not removable by the user we are deploying with (e.g. root created a file or ran a command or something like that).
The result was that the deployment was unsuccessful and a rollback was initiated. And in general you probably don't the deployment to fail because of a cleanup task that could not remove an old release directory.
Nevertheless I will check if this still is necessary and make this configurable.
Thanks for the hint.

**Comment by mwr** [comment]
In the latest version the cleanup is no longer overwritten by n98-deployer. The default deployer implementation is sufficient and supports an optional sudo.
