### ISSUE TITLE
setup:upgrade required in final env

### ISSUE THREAD

**Issue by barbazul** [netz98/n98-deployer#4]
I've noticed that after every deploy that adds or updates a module, the deployed environment dies and an error similar to this is shown:

```
There has been an error processing your request

Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory. 
The following modules are outdated:
Vendor_Module schema: current version - none, required version - 0.1.0
Vendor_Module data: current version - none, required version - 0.1.0
```

Effectively after running the suggested command in the environment everything works.

I am using the provided example pipeline which includes a step `MagentoTasks::TASK_SETUP_UPGRADE` and the corresponding output in Jenkins is

> ➤ Executing task magento:setup_upgrade
> ✔ Ok

So I looked under the hood and found that that task ends up running `\Deployer\run("php bin/magento setup:upgrade --keep-generated");` which seems to be ok, but I wondered about the `--keep-generated` flag.

Looking at the help for the flag it states: `Prevents generated files from being deleted.We discourage using this option except when deploying to production. Consult your system integrator or administrator for more information.`

So I am consulting with you guys. =D

To be honest, that doesn't _feel_ like it's the source of the issue but somehow magento is unaware of the run to setup:upgrade.

Maybe it is running in the wrong version folder?

**Comment by mwr** [comment]
I think the source of the problem is the database being re-used for different development branches.
You will get the same problem when developing a feature on a branch and adding a new module in that feature. Then running the database upgrade and thus adding it to the setup_module and the app/etc/config.php. Now when you are switching back to another branch that does not have this modules php source-code you will get this error.
So this error tends to happen on local development environments were you switch branches often. For development purposes we have a n98magerun2 command to "downgrade" the database entries in such a scenario.

If I understand you correctly the issue arises during deployment. 
Just to clarify: Did you remove the php sources of a module that was already present in the setup_module table and then run setup:upgrade?

**Comment by barbazul** [comment]
I am aware of the database-reuse issue and I am already looking for
alternatives to avoid it.

However, that is not the case I am reporting. The issue is arising when I
add a new module and then deploying to production.

The deployment is successful, but the application throws the setup upgrade
message.

I haven't yet looked into this myself as the store is not yet publicly
available so it is still not critical, but eventually I'll get to it.

**Comment by barbazul** [comment]
After stumbling with this problem some more, I am starting to believe this might be related to OPcode cache as it is also causing us trouble.

**Comment by barbazul** [comment]
I am closing this issue as it seems to have been a problem only on the production environment for one particular project.

I have since used this deployment library on other projects without this problem.
